AWSTemplateFormatVersion: 2010-09-09
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties: 
      BucketEncryption: ServerSideEncryptionByDefault
      BucketName: dl-fmwrk-xxxxx-us-east-1

  Type: AWS::SNS::Topic
  Properties: 
    DisplayName: dl-fmwrk-xxxxx-init-file-creation
    Subscription: 
    - Endpoint: arn:aws:lambda:us-east-1:076931226898:function:dlFmwrkSrcDataInfo
    - Protocol: Lambda
    Tags: 
    - Key: project
    - Value: aws-datalake-framework
    TopicName: dl-fmwrk-xxxxx-init-file-creation

  Type: AWS::SNS::TopicPolicy
  Properties:
    PolicyDocument:
      Id: dlFmwrkTopicId
      Version: '2012-10-17'
      Statement:
      - Sid: SNS Topic Policy for createObject event in S3
        Effect: Allow
        Principal:
          Service: s3.amazonaws.com
        Action: sns:Publish
        Resource: "arn:aws:sns:us-east-1:076931226898:dl-fmwrk-xxxxx-init-file-creation"
    Topics:
    - !Ref mytopic